data:
  train:
    root: 'data/md17'
    molecule_name: 'aspirin'
    down_sample_every: 10
    with_h: true
    span: 30
    mode: 'train'
    project: true

  val:
    root: 'data/md17'
    molecule_name: 'aspirin'
    down_sample_every: 10
    with_h: true
    span: 30
    mode: 'val'
    force_length: 256
    project: true

  test:
    root: 'data/md17'
    molecule_name: 'aspirin'
    down_sample_every: 10
    with_h: true
    span: 30
    mode: 'test'
    return_index: true
    project: true

wandb:
  wandb_usr: 'YOUR_USER_NAME'
  no_wandb: true
  project: 'traj_md17'

denoise_model:
  n_layers: 6
  node_dim: 30
  edge_dim: 4
  hidden_dim: 128
  time_emb_dim: 32
  act_fn: 'silu'
  learn_ref_frame: false
  n_layers_ref: 2
  num_w: 20  # span - len(cond_mask): 30 - 10 = 20

diffusion:
  beta_schedule_name: 'linear'
  num_timesteps: 100
  mode: 'uncond'

train:
  exp_name: 'md17_aspirin_GeoTDM_uncond'
  output_base_path: 'outputs/'
  seed: 100
  tot_len: 20
  num_epochs: 8000
  batch_size: 128
  eval_batch_size: 256
  lr: 0.0001
  save_model: true
  save_every_epoch: 500
  eval_every_epoch: 100
  log_every_step: 20
  final_test: true
  final_test_ckpt: 'best'  # Should be in ['last', 'best', epoch]
  K: 5

