data:
  root: 'data/md17'
  molecule_name: 'paracetamol'
  down_sample_every: 10
  with_h: true
  span: 30
  mode: 'test'
  return_index: true
  project: false  # true (false) for uncond (cond) generation

wandb:
  wandb_usr: 'YOUR_USER_NAME'
  no_wandb: true
  project: 'traj_md17'

eval:
  train_exp_name: 'paracetamol'  # The name of the training exp
  model_ckpt: 'best'
  eval_exp_name: null  # Default: train_exp_name + '_eval'
  output_base_path: 'outputs/'  # Should be the same as training
  cond_mask: null  # Default: The same as training
  cond: true  # use true if conditional and false if uncond
  seed: 2000
  model: 'GeoTDM'
  batch_size: 32
  sampling_timesteps: 1000  # Default: The same as training

